#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-asciidoctor
Version  : 1.5.2
Release  : 2
URL      : https://rubygems.org/downloads/asciidoctor-1.5.2.gem
Source0  : https://rubygems.org/downloads/asciidoctor-1.5.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-asciidoctor-bin
BuildRequires : ruby
BuildRequires : rubygem-coderay
BuildRequires : rubygem-cucumber
BuildRequires : rubygem-erubis
BuildRequires : rubygem-haml
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-slim
BuildRequires : rubygem-tilt

%description
= Asciidoctor
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>; Sarah White <https://github.com/graphitefriction[@graphitefriction]>; Ryan Waldron <https://github.com/erebor[@erebor]>
// settings:
:page-layout: base
:idprefix:
ifdef::env-github[:idprefix: user-content-]
:idseparator: -
:source-language: ruby
:language: {source-language}
// URIs:
:uri-org: https://github.com/asciidoctor
:uri-repo: {uri-org}/asciidoctor
:uri-asciidoctorj: {uri-org}/asciidoctorj
:uri-asciidoctorjs: {uri-org}/asciidoctor.js
:uri-project: http://asciidoctor.org
:uri-docs: {uri-project}/docs
:uri-news: {uri-project}/news
:uri-manpage: {uri-project}/man/asciidoctor
:uri-issues: {uri-repo}/issues
:uri-contributors: {uri-repo}/graphs/contributors
:uri-rel-file-base: link:
:uri-rel-tree-base: link:
ifdef::awestruct-version[]
:uri-rel-file-base: {uri-repo}/blob/master/
:uri-rel-tree-base: {uri-repo}/tree/master/
endif::[]
:uri-changelog: {uri-rel-file-base}CHANGELOG.adoc
:uri-contribute: {uri-rel-file-base}CONTRIBUTING.adoc
:uri-license: {uri-rel-file-base}LICENSE.adoc
:uri-tests: {uri-rel-tree-base}test
:uri-discuss: http://discuss.asciidoctor.org
:uri-irc: irc://irc.freenode.org/#asciidoctor
:uri-rubygem: http://rubygems.org/gems/asciidoctor
:uri-what-is-asciidoc: {uri-docs}/what-is-asciidoc
:uri-user-manual: {uri-docs}/user-manual
:uri-install-doc: {uri-docs}/install-toolchain
:uri-install-osx-doc: {uri-docs}/install-asciidoctor-macosx
:uri-render-doc: {uri-docs}/render-documents
:uri-themes-doc: {uri-docs}/produce-custom-themes-using-asciidoctor-stylesheet-factory
:uri-gitscm-repo: https://github.com/git/git-scm.com
:uri-prototype: {uri-gitscm-repo}/commits/master/lib/asciidoc.rb
:uri-freesoftware: https://www.gnu.org/philosophy/free-sw.html
:uri-foundation: http://foundation.zurb.com
:uri-tilt: https://github.com/rtomayko/tilt
// images:
:image-uri-screenshot: https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/screenshot.png

%package bin
Summary: bin components for the rubygem-asciidoctor package.
Group: Binaries

%description bin
bin components for the rubygem-asciidoctor package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n asciidoctor-1.5.2
gem spec %{SOURCE0} -l --ruby > rubygem-asciidoctor.gemspec

%build
gem build rubygem-asciidoctor.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
asciidoctor-1.5.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/asciidoctor-1.5.2
ruby -v -I"lib:test" test*/test_*.rb
ruby -v -I"lib:test" test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/asciidoctor-1.5.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/append-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/assign_caption-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/assign_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/block%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/blocks%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/blocks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/caption-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/captioned_title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/cdesc-AbstractBlock.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/content_model-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/context%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/find_by-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/inline%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/level-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/lineno-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/reindex_sections-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/remove_sub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/sections-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/source_location-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/style-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/sub%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/title%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractBlock/title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/attr%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/attr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/block%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/cdesc-AbstractNode.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/converter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/generate_data_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/generate_data_uri_from_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/has_role%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/icon_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/image_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/inline%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/is_uri%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/list_marker_keyword-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/media_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/node_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/normalize_asset_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/normalize_system_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/normalize_web_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/option%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/parent%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/parent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/read_asset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/reftext%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/reftext-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/relative_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/role%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/role-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/roles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/set_attr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/set_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AbstractNode/update_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/cdesc-AttributeList.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/parse_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/parse_attribute_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/parse_into-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/rekey-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/rekey-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/scan_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/scan_to_delimiter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/scan_to_quote-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/skip_blank-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/AttributeList/skip_delimiter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Block/cdesc-Block.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Block/content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Block/lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Block/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Block/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Block/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/callout_ids-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/cdesc-Callouts.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/current_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/generate_callout_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/generate_next_callout_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/next_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/read_next_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/register-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Callouts/rewind-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/cdesc-Invoker.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/documents-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/invoke%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/read_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/read_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/redirect_streams-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Invoker/reset_streams-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Options/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Options/parse%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Options/parse%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/Options/print_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Cli/cdesc-Cli.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Compliance/cdesc-Compliance.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Compliance/define-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Compliance/keys-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BackendInfo/backend_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BackendInfo/basebackend-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BackendInfo/cdesc-BackendInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BackendInfo/filetype-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BackendInfo/htmlsyntax-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BackendInfo/outfilesuffix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BackendInfo/setup_backend_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BuiltIn/cdesc-BuiltIn.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BuiltIn/content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BuiltIn/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BuiltIn/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BuiltIn/pass-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/BuiltIn/skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/CompositeConverter/cdesc-CompositeConverter.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/CompositeConverter/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/CompositeConverter/convert_with_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/CompositeConverter/converter_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/CompositeConverter/converters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/CompositeConverter/find_converter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/CompositeConverter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Config/register_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/admonition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/author_element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/cdesc-DocBook45Converter.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/common_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/doctype_declaration-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/document_info_element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/document_ns_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/inline_anchor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/lang_attribute_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook45Converter/olist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/admonition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/author_element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/cdesc-DocBook5Converter.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/colist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/common_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/dlist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/doctype_declaration-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/document_info_element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/document_ns_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/document_title_tags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/example-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/floating_title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/image-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_anchor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_break-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_button-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_callout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_footnote-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_image-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_indexterm-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_kbd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_menu-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/inline_quoted-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/lang_attribute_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/listing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/literal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/olist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/open-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/page_break-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/paragraph-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/preamble-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/quote-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/resolve_content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/sidebar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/stem-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/thematic_break-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/title_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/ulist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/DocBook5Converter/verse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/cdesc-Factory.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/converters-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/converters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/create-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/default-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/register-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/register-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/resolve-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/resolve-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/unregister_all-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Factory/unregister_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/admonition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/append_boolean_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/audio-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/cdesc-Html5Converter.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/colist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/dlist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/embedded-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/example-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/floating_title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/image-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_anchor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_break-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_button-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_callout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_footnote-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_image-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_indexterm-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_kbd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_menu-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/inline_quoted-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/listing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/literal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/olist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/open-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/outline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/page_break-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/paragraph-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/preamble-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/quote-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/sidebar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/stem-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/thematic_break-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/toc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/ulist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/verse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/Html5Converter/video-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/ThreadSafe/cdesc-ThreadSafe.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/caches-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/cdesc-TemplateConverter.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/clear_caches-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/handles%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/load_eruby-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/register-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/scan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/scan_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/TemplateConverter/templates-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/cdesc-Converter.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/convert_with_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Converter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/AttributeEntry/cdesc-AttributeEntry.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/AttributeEntry/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/AttributeEntry/negate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/AttributeEntry/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/AttributeEntry/save_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/AttributeEntry/value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/Title/cdesc-Title.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/Title/combined-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/Title/main-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/Title/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/Title/sanitized%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/Title/subtitle%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/Title/subtitle-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/Title/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/apply_attribute_value_subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/attribute_locked%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/author-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/backend-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/base_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/basebackend%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/callouts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/clear_playback_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/compat_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/converter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/counter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/counter_increment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/counters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/create_converter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/delete_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/docinfo-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/docinfo_processors%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/doctitle-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/doctype-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/embedded%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/extensions%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/finalize_header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/first_section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/footnotes%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/footnotes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/has_header%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/header%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/nested%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/nextval-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/nofooter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/noheader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/notitle-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/parent_document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/playback_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/reader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/references-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/register-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/restore_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/revdate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/safe-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/save_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/set_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/source_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/sourcemap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/title%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/update_backend_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/update_doctype_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Document/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockMacroProcessor/cdesc-BlockMacroProcessor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessor/cdesc-BlockProcessor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessor/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessor/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/bind_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/cdesc-BlockProcessorDsl.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/content_model-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/contexts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/default_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/match_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/name_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/name_positional_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/named-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/on_context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/on_contexts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/parse_content_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/pos_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/positional_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/BlockProcessorDsl/seed_attributes_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/DSL/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/DSL/using_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/DocinfoProcessor/cdesc-DocinfoProcessor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/DocinfoProcessor/location-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/DocinfoProcessor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/DocinfoProcessor/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/DocinfoProcessorDsl/at_location-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/DocinfoProcessorDsl/cdesc-DocinfoProcessorDsl.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Extension/cdesc-Extension.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Extension/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Extension/instance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Extension/kind-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Extension/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Group/activate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Group/cdesc-Group.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Group/register-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/IncludeProcessor/cdesc-IncludeProcessor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/IncludeProcessor/handles%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/IncludeProcessor/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/InlineMacroProcessor/cdesc-InlineMacroProcessor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/InlineMacroProcessor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/InlineMacroProcessor/resolve_regexp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/InlineMacroProcessorDsl/cdesc-InlineMacroProcessorDsl.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/InlineMacroProcessorDsl/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/InlineMacroProcessorDsl/using_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessor/cdesc-MacroProcessor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessor/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessor/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/bind_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/cdesc-MacroProcessorDsl.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/content_model-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/default_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/match_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/name_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/name_positional_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/named-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/parse_content_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/pos_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/positional_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/MacroProcessorDsl/seed_attributes_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Postprocessor/cdesc-Postprocessor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Postprocessor/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Preprocessor/cdesc-Preprocessor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Preprocessor/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/cdesc-Processor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/config-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/create_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/create_image_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/create_inline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/extend_dsl-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/include_dsl-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/option-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/parse_content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/update_config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Processor/use_dsl-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/ProcessorDsl/cdesc-ProcessorDsl.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/ProcessorDsl/option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/ProcessorDsl/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/ProcessorDsl/process_block_given%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/ProcessorExtension/cdesc-ProcessorExtension.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/ProcessorExtension/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/ProcessorExtension/process_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/activate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/add_document_processor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/add_syntax_processor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/as_symbol-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/block_macro-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/block_macros%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/blocks%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/cdesc-Registry.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/docinfo_processor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/docinfo_processors%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/docinfo_processors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/find_block_extension-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/find_block_macro_extension-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/find_inline_macro_extension-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/groups-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/include_processor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/include_processors%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/include_processors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/inline_macro-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/inline_macros%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/inline_macros-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/postprocessor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/postprocessors%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/postprocessors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/preprocessor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/preprocessors%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/preprocessors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/registered_for_block%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/registered_for_block_macro%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/registered_for_inline_macro%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/resolve_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/treeprocessor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/treeprocessors%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Registry/treeprocessors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Treeprocessor/cdesc-Treeprocessor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/Treeprocessor/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/build_registry-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/cdesc-Extensions.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/class_for_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/generate_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/groups-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/next_auto_id-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/register-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/resolve_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Extensions/unregister_all-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Helpers/cdesc-Helpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Helpers/encode_uri-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Helpers/mkdir_p-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Helpers/normalize_lines-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Helpers/normalize_lines_array-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Helpers/normalize_lines_from_string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Helpers/require_library-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Helpers/rootname-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Inline/block%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Inline/cdesc-Inline.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Inline/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Inline/inline%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Inline/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Inline/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Inline/target-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Inline/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Inline/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/List/cdesc-List.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/List/content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/List/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/List/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/List/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/List/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/ListItem/cdesc-ListItem.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/ListItem/fold_first-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/ListItem/marker-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/ListItem/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/ListItem/text%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/ListItem/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/ListItem/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/build_block-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/catalog_callouts-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/catalog_inline_anchors-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/cdesc-Parser.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/initialize_section-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/is_delimited_block%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/is_next_line_document_title%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/is_next_line_section%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/is_section_title%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/is_sibling_list_item%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/is_single_line_section_title%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/is_two_line_section_title%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/line_length-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/next_block-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/next_labeled_list-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/next_list_item-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/next_outline_list-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/next_section-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/next_table-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_block_metadata_line-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_block_metadata_lines-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_blocks-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_cell_spec-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_col_specs-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_document_header-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_header_metadata-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_manpage_header-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_section_title-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/parse_style_attribute-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/process_attribute_entries-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/process_attribute_entry-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/process_authors-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/read_lines_for_list_item-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/reset_block_indent%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/resolve_list_marker-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/resolve_ordered_list_marker-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/roman_numeral_to_int-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/sanitize_attribute_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/section_level-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/single_line_section_level-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Parser/store_attribute-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/cdesc-PathResolver.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/expand_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/file_separator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/is_root%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/is_unc%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/is_web_root%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/join_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/partition_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/posixfy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/relative_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/system_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/web_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PathResolver/working_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/cdesc-PreprocessorReader.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/exceeded_max_depth%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/include_depth-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/include_processors%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/include_stack-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/includes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/peek_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/pop_include-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/prepare_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/preprocess_conditional_inclusion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/preprocess_include-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/process_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/push_include-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/resolve_expr_val-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/shift-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/skip_front_matter%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/PreprocessorReader/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/Cursor/cdesc-Cursor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/Cursor/dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/Cursor/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/Cursor/line_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/Cursor/lineno-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/Cursor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/Cursor/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/Cursor/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/advance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/cdesc-Reader.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/cursor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/eof%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/has_more_lines%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/line_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/lineno-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/next_line_empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/next_line_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/peek_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/peek_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/prepare_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/prev_line_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/process_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/process_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/read_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/read_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/read_lines_until-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/readlines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/replace_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/restore_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/restore_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/shift-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/skip_blank_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/skip_comment_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/skip_line_comments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/source_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/terminate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/unshift-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/unshift_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Reader/unshift_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/SafeMode/cdesc-SafeMode.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/cdesc-Section.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/generate_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/number-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/numbered-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/sectname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/sectnum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/special-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Section/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/cdesc-Stylesheets.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/coderay_stylesheet_data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/coderay_stylesheet_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/embed_coderay_stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/embed_primary_stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/embed_pygments_stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/instance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/load_pygments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/primary_stylesheet_data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/primary_stylesheet_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/pygments_stylesheet_data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/pygments_stylesheet_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/write_coderay_stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/write_primary_stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Stylesheets/write_pygments_stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/apply_header_subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/apply_normal_subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/apply_subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/apply_title_subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/cdesc-Substitutors.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/convert_quoted_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/do_replacement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/extract_passthroughs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/highlight_source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/lock_in_subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/normalize_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/parse_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/parse_quoted_text_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/passthroughs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/resolve_block_subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/resolve_pass_subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/resolve_subs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/restore_passthroughs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/split_simple_csv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_callouts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_inline_anchors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_inline_xrefs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_macros-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_post_replacements-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_quotes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_replacements-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_specialcharacters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/sub_specialchars-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/unescape_bracketed_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Substitutors/unescape_brackets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Cell/cdesc-Cell.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Cell/colspan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Cell/content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Cell/inner_document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Cell/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Cell/rowspan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Cell/style-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Cell/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Cell/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Column/assign_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Column/cdesc-Column.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Column/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Column/style-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/activate_rowspan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/advance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/buffer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/buffer_has_unclosed_quotes%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/buffer_quoted%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/cdesc-ParserContext.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/cell_closed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/cell_open%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/close_cell-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/close_open_cell-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/close_row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/col_count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/delimiter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/delimiter_re-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/effective_col_visits-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/end_of_row%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/keep_cell_open-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/mark_cell_closed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/match_delimiter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/push_cell_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/skip_matched_delimiter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/starts_with_delimiter%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/ParserContext/take_cell_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Rows/body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Rows/cdesc-Rows.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Rows/foot-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Rows/head-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/Rows/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/cdesc-Table.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/columns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/create_columns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/has_header_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/header_row%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/partition_header_footer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Table/rows-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Timings/cdesc-Timings.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Timings/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Timings/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Timings/print_report-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Timings/read_parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Timings/read_parse_convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Timings/record-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Timings/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Timings/total-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/VoidWriter/cdesc-VoidWriter.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/VoidWriter/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Writer/cdesc-Writer.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/Writer/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/cdesc-Asciidoctor.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/convert-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/convert_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/load_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/render-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Asciidoctor/render_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Comparable/%3c%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Comparable/%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Comparable/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Comparable/%3e%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Comparable/%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Comparable/cdesc-Comparable.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Dir/cdesc-Dir.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Dir/getwd-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Dir/home-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Dir/pwd-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/basename-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/cdesc-File.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/dirname-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/each_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/eof-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/expand_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/extname-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/file%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/join-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/lineno-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/read-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/File/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Kernel/cdesc-Kernel.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Kernel/open-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/NilClass/cdesc-NilClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Numeric/cdesc-Numeric.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/SecurityError/cdesc-SecurityError.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/String/chr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Symbol/cdesc-Symbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/Symbol/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/asciidoctor-1.5.2/ri/page-LICENSE_adoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/CHANGELOG.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/LICENSE.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/README.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/benchmark/benchmark.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/benchmark/sample-data/mdbasics.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/bin/asciidoctor
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/bin/asciidoctor-safe
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/compat/asciidoc.conf
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/compat/font-awesome-3-compat.css
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/data/stylesheets/asciidoctor-default.css
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/data/stylesheets/coderay-asciidoctor.css
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/features/open_block.feature
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/features/pass_block.feature
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/features/step_definitions.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/features/text_formatting.feature
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/features/xref.feature
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_node.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/attribute_list.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/block.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/callouts.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/options.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/composite.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/docbook45.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/docbook5.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/factory.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/html5.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/converter/template.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/core_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/core_ext/object/nil_or_empty.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/core_ext/string/chr.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/core_ext/symbol/length.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/inline.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/list.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/opal_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/opal_ext/comparable.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/opal_ext/dir.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/opal_ext/error.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/opal_ext/file.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/path_resolver.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/reader.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/section.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/stylesheets.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/substitutors.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/table.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/timings.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/man/asciidoctor.1
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/man/asciidoctor.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/attributes_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/blocks_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/converter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/document_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/extensions_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/asciidoc_index.txt
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/basic-docinfo-footer.html
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/basic-docinfo-footer.xml
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/basic-docinfo.html
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/basic-docinfo.xml
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/basic.asciidoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/chapter-a.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/child-include.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-backends/erb/html5/block_paragraph.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-backends/haml/docbook45/block_paragraph.xml.haml
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-backends/haml/html5-tweaks/block_paragraph.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-backends/haml/html5/block_paragraph.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-backends/haml/html5/block_sidebar.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-backends/slim/docbook45/block_paragraph.xml.slim
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-backends/slim/html5/block_paragraph.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-backends/slim/html5/block_sidebar.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-docinfodir/basic-docinfo.html
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/custom-docinfodir/docinfo.html
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/docinfo-footer.html
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/docinfo-footer.xml
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/docinfo.html
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/docinfo.xml
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/dot.gif
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/encoding.asciidoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/grandchild-include.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/hello-asciidoctor.pdf
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/include-file.asciidoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/include-file.xml
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/master.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/parent-include-restricted.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/parent-include.adoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/sample.asciidoc
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/stylesheets/custom.css
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/fixtures/tip.gif
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/invoker_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/links_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/lists_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/options_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/paragraphs_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/parser_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/paths_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/preamble_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/reader_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/sections_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/substitutions_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/tables_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/test/text_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/asciidoctor-1.5.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/asciidoctor
/usr/bin/asciidoctor-safe
